// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return web; // Web options are commonly used for Windows desktop Firebase
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO3ieRr5KCyIEt3_sDbgBYPdpEY0cpHzk',
    appId: '1:921397124091:web:125d2240ea943aef25c95e',
    messagingSenderId: '921397124091',
    projectId: 'estudieo-3405c',
    authDomain: 'estudieo-3405c.firebaseapp.com',
    storageBucket: 'estudieo-3405c.firebasestorage.app',
    measurementId: 'G-0VXCGG574N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhNMOp0jMbpHUHnQjLa1yqt6UvSPLP-7w',
    appId: '1:921397124091:android:95368d3a49251e1125c95e',
    messagingSenderId: '921397124091',
    projectId: 'estudieo-3405c',
    storageBucket: 'estudieo-3405c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO3ieRr5KCyIEt3_sDbgBYPdpEY0cpHzk',
    appId: '1:921397124091:ios:125d2240ea943aef25c95e',
    messagingSenderId: '921397124091',
    projectId: 'estudieo-3405c',
    storageBucket: 'estudieo-3405c.firebasestorage.app',
    iosClientId:
        '921397124091-k4jfbijukgjspsm0l4k089dcjtuqjenl.apps.googleusercontent.com',
    iosBundleId: 'com.example.learn',
  );
}
